### ISSUE TITLE
Icon button variation

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-atomic#39]
##### Expected Behavior
When an icon displays with text, the icon should just be a decorator and should not be clickable. We should not provide a pattern that combines an icon with text where the icon is clickable. Additionally, the text would be blue (like a link) and the icon would be gray.

##### Actual Behavior
The Icon button variation includes an example of icon with text wrapped within a button. These examples should be removed.

**Comment by andresgalante** [comment]
Should be done 😄
